### ISSUE TITLE
[Feature Request] Targeted Media App Kill

### ISSUE THREAD

**Issue by simonlokk** [ginsudev/KillControl#1]
Thanks for taking the time to create this tweak! I have a specific use case that others may find usefull. I find (as others) that the Apple Music App randomly will deplete my battery if left running (while not playing) in the background. Shazam randomly does this as well on both IOS 14 and 15. It would be great if KillControl can target one specific App to kill on lock rather than blacklisting everything but that app and then kill the targeted Music App (in this example) on lock only if it is not actively playing, but leave it alone if it is.

On a side note, I have noticed that pulling down only kills all on the top row off running apps (at least on an Ipad running 14.8)

Thanks again!

**Comment by ginsudev** [comment]
> Thanks for taking the time to create this tweak! I have a specific use case that others may find usefull. I find (as others) that the Apple Music App randomly will deplete my battery if left running (while not playing) in the background. Shazam randomly does this as well on both IOS 14 and 15. It would be great if KillControl can target one specific App to kill on lock rather than blacklisting everything but that app and then kill the targeted Music App (in this example) on lock only if it is not actively playing, but leave it alone if it is.
> 
> 
> 
> On a side note, I have noticed that pulling down only kills all on the top row off running apps (at least on an Ipad running 14.8)
> 
> 
> 
> Thanks again!

Thanks for the request. I've just released v1.0.1 which adds an option to only kill chosen apps when locked. I'll improve upon this feature in v1.0.2 and make it so that media apps will only get killed if they aren't playing anything (when locked & this new option is enabled).
